version: '2'
services:
  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    volumes:
      - ./src:/code
    links:
      - db:db
      - redis:redis
    env_file:
      - .env
    ports:
      - "${HOST_DEV_PORT_APP}:80"
    command: python manage.py runserver 0.0.0.0:80

  db:
    image: postgres:alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${HOST_DEV_PORT_DB}:5432"
#
#  scheduler:
#    build:
#      context: .
#      dockerfile: ./.docker/app/Dockerfile
#    volumes:
#      - ./src:/code
#    links:
#      - db:db
#      - redis:redis
#    env_file:
#      - .env.dev
#    command: celery -A project beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
#
#  worker:
#    build:
#      context: .
#      dockerfile: ./.docker/app/Dockerfile
#    volumes:
#      - ./src:/code
#    links:
#      - db:db
#      - redis:redis
#    env_file:
#      - .env.dev
#    command: celery -A project worker -l debug

  redis:
    image: redis:alpine
volumes:
  db:
